#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$REPO_DIR"

if [[ -n "$(git status --porcelain)" ]]; then
  echo "Working tree is dirty, refusing to run." >&2
  exit 1
fi

git checkout main --quiet
git pull --rebase --quiet

LATEST_LOG=$(ls -t log/*.md 2>/dev/null | head -1 || true)
if [[ -z "$LATEST_LOG" ]]; then
  echo "No logs found, nothing to do."
  exit 0
fi

if [[ -f next-workout.md ]] && [[ "$LATEST_LOG" -ot next-workout.md ]]; then
  echo "next-workout.md is newer than $LATEST_LOG, nothing to do."
  exit 0
fi

EXISTING_PR=$(gh pr list --state open --json headRefName --jq \
  '[.[] | select(.headRefName | startswith("next-workout/"))] | length')
if [[ "$EXISTING_PR" -gt 0 ]]; then
  echo "An open next-workout PR already exists, skipping."
  exit 0
fi

LOG_BASE=$(basename "$LATEST_LOG" .md)
BRANCH="next-workout/$LOG_BASE"

git checkout -b "$BRANCH" --quiet

claude -p "/personal-trainer" --permission-mode acceptEdits

if git diff --quiet && git diff --cached --quiet; then
  echo "Skill produced no changes."
  git checkout main --quiet
  git branch -D "$BRANCH" --quiet
  exit 0
fi

git add next-workout.md next-workouts/ training-plan.md 2>/dev/null || true
git commit -m "Generate next workout from $LOG_BASE"
git push -u origin "$BRANCH" --quiet

gh pr create \
  --title "Next workout from $LOG_BASE" \
  --body "Auto-generated by the personal-trainer skill from log \`$LOG_BASE\`."
